/** Generated by scripts/gallery-publish.js — do not edit by hand. */
export type GalleryCaseRole = 'before' | 'after' | 'other';

export interface GalleryCaseImage {
  src: string;
  role: GalleryCaseRole;
  alt: string;
}

export interface GalleryCase {
  id: string;
  order: number;
  procedure: string;
  caption: string;
  display: 'pair' | 'composite';
  before: GalleryCaseImage | null;
  after: GalleryCaseImage | null;
  images: GalleryCaseImage[];
}

export const galleryCases: GalleryCase[] = [
  {
    id: 'case-1',
    order: 1,
    procedure: 'Cosmetic Dentistry',
    caption: 'Cosmetic Bonding for Diastema Closure',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0804.JPG', role: 'before', alt: 'Before — Cosmetic Bonding for Diastema Closure' },
    after: { src: '/images/gallery/DSC_0818.JPG', role: 'after', alt: 'After — Cosmetic Bonding for Diastema Closure' },
    images: [
      { src: '/images/gallery/DSC_0804.JPG', role: 'before', alt: 'Before — Cosmetic Bonding for Diastema Closure' },
      { src: '/images/gallery/DSC_0818.JPG', role: 'after', alt: 'After — Cosmetic Bonding for Diastema Closure' }
    ],
  },
  {
    id: 'case-2',
    order: 2,
    procedure: 'Crowns & Bridges',
    caption: 'Cracked Front Crown Replacement',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0002.JPG', role: 'before', alt: 'Before — Cracked Front Crown Replacement' },
    after: { src: '/images/gallery/DSC_0107.JPG', role: 'after', alt: 'After — Cracked Front Crown Replacement' },
    images: [
      { src: '/images/gallery/DSC_0002.JPG', role: 'before', alt: 'Before — Cracked Front Crown Replacement' },
      { src: '/images/gallery/DSC_0107.JPG', role: 'after', alt: 'After — Cracked Front Crown Replacement' }
    ],
  },
  {
    id: 'case-3',
    order: 3,
    procedure: 'Cosmetic Dentistry',
    caption: 'Cosmetic Bonding for Chipped Front Tooth',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0021.JPG', role: 'before', alt: 'Before — Cosmetic Bonding for Chipped Front Tooth' },
    after: { src: '/images/gallery/DSC_0025.JPG', role: 'after', alt: 'After — Cosmetic Bonding for Chipped Front Tooth' },
    images: [
      { src: '/images/gallery/DSC_0021.JPG', role: 'before', alt: 'Before — Cosmetic Bonding for Chipped Front Tooth' },
      { src: '/images/gallery/DSC_0025.JPG', role: 'after', alt: 'After — Cosmetic Bonding for Chipped Front Tooth' }
    ],
  },
  {
    id: 'case-4',
    order: 4,
    procedure: 'Veneers',
    caption: 'Porcelain Veneer Smile Makeover',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0684.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
    after: { src: '/images/gallery/DSC_0768.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' },
    images: [
      { src: '/images/gallery/DSC_0684.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0706.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0707.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0768.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0769.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0770.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' }
    ],
  },
  {
    id: 'case-5',
    order: 5,
    procedure: 'Cosmetic Dentistry',
    caption: 'Chipped Tooth Cosmetic Bonding',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0844.JPG', role: 'before', alt: 'Before — Chipped Tooth Cosmetic Bonding' },
    after: { src: '/images/gallery/DSC_0846.JPG', role: 'after', alt: 'After — Chipped Tooth Cosmetic Bonding' },
    images: [
      { src: '/images/gallery/DSC_0844.JPG', role: 'before', alt: 'Before — Chipped Tooth Cosmetic Bonding' },
      { src: '/images/gallery/DSC_0846.JPG', role: 'after', alt: 'After — Chipped Tooth Cosmetic Bonding' }
    ],
  },
  {
    id: 'case-6',
    order: 6,
    procedure: 'Cosmetic Dentistry',
    caption: 'White Spot Cosmetic Treatment',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0968.JPG', role: 'before', alt: 'Before — White Spot Cosmetic Treatment' },
    after: { src: '/images/gallery/DSC_0977.JPG', role: 'after', alt: 'After — White Spot Cosmetic Treatment' },
    images: [
      { src: '/images/gallery/DSC_0968.JPG', role: 'before', alt: 'Before — White Spot Cosmetic Treatment' },
      { src: '/images/gallery/DSC_0977.JPG', role: 'after', alt: 'After — White Spot Cosmetic Treatment' }
    ],
  },
  {
    id: 'case-7',
    order: 7,
    procedure: 'Veneers',
    caption: 'Porcelain Veneer for Chipped Front Tooth',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0928.JPG', role: 'before', alt: 'Before — Porcelain Veneer for Chipped Front Tooth' },
    after: { src: '/images/gallery/DSC_0933.JPG', role: 'after', alt: 'After — Porcelain Veneer for Chipped Front Tooth' },
    images: [
      { src: '/images/gallery/DSC_0928.JPG', role: 'before', alt: 'Before — Porcelain Veneer for Chipped Front Tooth' },
      { src: '/images/gallery/DSC_0933.JPG', role: 'after', alt: 'After — Porcelain Veneer for Chipped Front Tooth' }
    ],
  },
  {
    id: 'case-8',
    order: 8,
    procedure: 'Veneers',
    caption: 'Porcelain Veneer Smile Makeover',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0314.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
    after: { src: '/images/gallery/DSC_0861.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' },
    images: [
      { src: '/images/gallery/DSC_0314.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0316.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0319.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0861.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0864.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0865.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' }
    ],
  },
  {
    id: 'case-9',
    order: 9,
    procedure: 'Dentures',
    caption: 'Custom Complete Denture Smile Restoration',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0796.JPG', role: 'before', alt: 'Before — Custom Complete Denture Smile Restoration' },
    after: { src: '/images/gallery/DSC_0539.JPG', role: 'after', alt: 'After — Custom Complete Denture Smile Restoration' },
    images: [
      { src: '/images/gallery/DSC_0796.JPG', role: 'before', alt: 'Before — Custom Complete Denture Smile Restoration' },
      { src: '/images/gallery/DSC_0539.JPG', role: 'after', alt: 'After — Custom Complete Denture Smile Restoration' }
    ],
  },
  {
    id: 'case-10',
    order: 10,
    procedure: 'Veneers',
    caption: 'Lower Arch Porcelain Veneers',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0079.JPG', role: 'before', alt: 'Before — Lower Arch Porcelain Veneers' },
    after: { src: '/images/gallery/DSC_0080.JPG', role: 'after', alt: 'After — Lower Arch Porcelain Veneers' },
    images: [
      { src: '/images/gallery/DSC_0079.JPG', role: 'before', alt: 'Before — Lower Arch Porcelain Veneers' },
      { src: '/images/gallery/DSC_0080.JPG', role: 'after', alt: 'After — Lower Arch Porcelain Veneers' }
    ],
  },
  {
    id: 'case-11',
    order: 11,
    procedure: 'Cosmetic Dentistry',
    caption: 'Anterior Cosmetic Smile Treatment',
    display: 'pair',
    before: { src: '/images/gallery/DSC_1015.JPG', role: 'before', alt: 'Before — Anterior Cosmetic Smile Treatment' },
    after: { src: '/images/gallery/DSC_0001.JPG', role: 'after', alt: 'After — Anterior Cosmetic Smile Treatment' },
    images: [
      { src: '/images/gallery/DSC_1015.JPG', role: 'before', alt: 'Before — Anterior Cosmetic Smile Treatment' },
      { src: '/images/gallery/DSC_0001.JPG', role: 'after', alt: 'After — Anterior Cosmetic Smile Treatment' }
    ],
  },
  {
    id: 'case-12',
    order: 12,
    procedure: 'Veneers',
    caption: 'Peg Lateral Incisor Veneer',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0228.JPG', role: 'before', alt: 'Before — Peg Lateral Incisor Veneer' },
    after: { src: '/images/gallery/DSC_0238.JPG', role: 'after', alt: 'After — Peg Lateral Incisor Veneer' },
    images: [
      { src: '/images/gallery/DSC_0228.JPG', role: 'before', alt: 'Before — Peg Lateral Incisor Veneer' },
      { src: '/images/gallery/DSC_0238.JPG', role: 'after', alt: 'After — Peg Lateral Incisor Veneer' }
    ],
  },
  {
    id: 'case-14',
    order: 14,
    procedure: 'Veneers',
    caption: 'Upper Arch Porcelain Veneers',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0040.JPG', role: 'before', alt: 'Before — Upper Arch Porcelain Veneers' },
    after: { src: '/images/gallery/DSC_0417.JPG', role: 'after', alt: 'After — Upper Arch Porcelain Veneers' },
    images: [
      { src: '/images/gallery/DSC_0040.JPG', role: 'before', alt: 'Before — Upper Arch Porcelain Veneers' },
      { src: '/images/gallery/DSC_0417.JPG', role: 'after', alt: 'After — Upper Arch Porcelain Veneers' }
    ],
  },
  {
    id: 'case-18',
    order: 18,
    procedure: 'Veneers',
    caption: 'Porcelain Veneer Smile Makeover',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0736.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
    after: { src: '/images/gallery/DSC_0843.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' },
    images: [
      { src: '/images/gallery/DSC_0736.JPG', role: 'before', alt: 'Before — Porcelain Veneer Smile Makeover' },
      { src: '/images/gallery/DSC_0843.JPG', role: 'after', alt: 'After — Porcelain Veneer Smile Makeover' }
    ],
  },
  {
    id: 'case-19',
    order: 19,
    procedure: 'Full Arch',
    caption: 'Maxillary Full Arch Restoration',
    display: 'pair',
    before: { src: '/images/gallery/DSC_0721.JPG', role: 'before', alt: 'Before — Maxillary Full Arch Restoration' },
    after: { src: '/images/gallery/DSC_0791.JPG', role: 'after', alt: 'After — Maxillary Full Arch Restoration' },
    images: [
      { src: '/images/gallery/DSC_0721.JPG', role: 'before', alt: 'Before — Maxillary Full Arch Restoration' },
      { src: '/images/gallery/DSC_0791.JPG', role: 'after', alt: 'After — Maxillary Full Arch Restoration' }
    ],
  },
  {
    id: 'case-15',
    order: 15,
    procedure: 'Dentures',
    caption: 'Complete Denture Smile Transformation',
    display: 'composite',
    before: null,
    after: { src: '/images/gallery/IG-Jack-BA.001.jpeg', role: 'other', alt: 'Result — Complete Denture Smile Transformation' },
    images: [
      { src: '/images/gallery/IG-Jack-BA.001.jpeg', role: 'other', alt: 'Result — Complete Denture Smile Transformation' }
    ],
  },
  {
    id: 'case-16',
    order: 16,
    procedure: 'Veneers',
    caption: 'Anterior Porcelain Veneers',
    display: 'composite',
    before: null,
    after: { src: '/images/gallery/IG-Ow1.001.jpeg', role: 'other', alt: 'Result — Anterior Porcelain Veneers' },
    images: [
      { src: '/images/gallery/IG-Ow1.001.jpeg', role: 'other', alt: 'Result — Anterior Porcelain Veneers' }
    ],
  },
  {
    id: 'case-17',
    order: 17,
    procedure: 'Dentures',
    caption: 'Complete Denture Transformation',
    display: 'composite',
    before: null,
    after: { src: '/images/gallery/IG-Soll-mx%20solo.001.jpeg', role: 'other', alt: 'Result — Complete Denture Transformation' },
    images: [
      { src: '/images/gallery/IG-Soll-mx%20solo.001.jpeg', role: 'other', alt: 'Result — Complete Denture Transformation' }
    ],
  },
  {
    id: 'case-20',
    order: 20,
    procedure: 'Smile Makeover',
    caption: 'Full Mouth Smile Restoration',
    display: 'composite',
    before: null,
    after: { src: '/images/gallery/IG-Sink%20comp-BA.jpeg', role: 'other', alt: 'Result — Full Mouth Smile Restoration' },
    images: [
      { src: '/images/gallery/IG-Sink%20comp-BA.jpeg', role: 'other', alt: 'Result — Full Mouth Smile Restoration' }
    ],
  },
  {
    id: 'case-21',
    order: 21,
    procedure: 'Full Arch',
    caption: 'Full Arch Restoration Comparison',
    display: 'composite',
    before: null,
    after: { src: '/images/gallery/IG-Soll-O.001.jpeg', role: 'other', alt: 'Result — Full Arch Restoration Comparison' },
    images: [
      { src: '/images/gallery/IG-Soll-O.001.jpeg', role: 'other', alt: 'Result — Full Arch Restoration Comparison' }
    ],
  },
  {
    id: 'case-22',
    order: 22,
    procedure: 'Full Arch',
    caption: 'Mandibular Full Arch Restoration',
    display: 'composite',
    before: null,
    after: { src: '/images/gallery/IG-Soll-mn.001.jpeg', role: 'other', alt: 'Result — Mandibular Full Arch Restoration' },
    images: [
      { src: '/images/gallery/IG-Soll-mn.001.jpeg', role: 'other', alt: 'Result — Mandibular Full Arch Restoration' }
    ],
  },
  {
    id: 'case-23',
    order: 23,
    procedure: 'Full Arch',
    caption: 'Full Arch Smile Transformation',
    display: 'composite',
    before: null,
    after: { src: '/images/gallery/IG-Lanc-BA.jpeg', role: 'other', alt: 'Result — Full Arch Smile Transformation' },
    images: [
      { src: '/images/gallery/IG-Lanc-BA.jpeg', role: 'other', alt: 'Result — Full Arch Smile Transformation' }
    ],
  },
  {
    id: 'case-24',
    order: 24,
    procedure: 'Full Arch',
    caption: 'Full Arch Before and After',
    display: 'composite',
    before: null,
    after: { src: '/images/gallery/IG-Soll.001.jpeg', role: 'other', alt: 'Result — Full Arch Before and After' },
    images: [
      { src: '/images/gallery/IG-Soll.001.jpeg', role: 'other', alt: 'Result — Full Arch Before and After' }
    ],
  }
];
